/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bankorea_solbus_jni_MessageQueue */

#ifndef _Included_com_bankorea_solbus_jni_MessageQueue
#define _Included_com_bankorea_solbus_jni_MessageQueue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CPWSWAOC
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CPWSWAOC
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CPWRWAOC
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CPWRWAOC
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CP02WAOC
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CP02WAOC
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CP03WAOC
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CP03WAOC
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CP04WAOC
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CP04WAOC
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CP05WAOC
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CP05WAOC
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CP12WAOC
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CP12WAOC
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CPWRDAIC
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CPWRDAIC
  (JNIEnv *, jobject);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CPWSDAIC
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CPWSDAIC
  (JNIEnv *, jobject);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CPWSDAOC
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CPWSDAOC
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CPWRDAOC
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CPWRDAOC
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CPWSWAIC
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CPWSWAIC
  (JNIEnv *, jobject);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CPMADAOC
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CPMADAOC
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CPMADAIC
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CPMADAIC
  (JNIEnv *, jobject);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CPAMDAOC
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CPAMDAOC
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CPAMDAIC
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CPAMDAIC
  (JNIEnv *, jobject);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CPHFJAOC
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CPHFJAOC
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CPHFNAIC
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CPHFNAIC
  (JNIEnv *, jobject);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CPBFJAOC
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CPBFJAOC
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CBFNAIC
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CBFNAIC
  (JNIEnv *, jobject);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CPFHJAOC
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CPFHJAOC
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CPFHCAOC
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CPFHCAOC
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CBFHJAIC
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CBFHJAIC
  (JNIEnv *, jobject);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CPHJNAOC
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CPHJNAOC
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CPHCNAOC
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CPHCNAOC
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CPHFJAIC
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CPHFJAIC
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CP99EAIC
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CP99EAIC
  (JNIEnv *, jobject);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CP99AAIC
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CP99AAIC
  (JNIEnv *, jobject);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CP99VAIC
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CP99VAIC
  (JNIEnv *, jobject);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CP99CAOC
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CP99CAOC
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CP99AAOC
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CP99AAOC
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_bankorea_solbus_jni_MessageQueue
 * Method:    CP99VAOC
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_bankorea_solbus_jni_MessageQueue_CP99VAOC
  (JNIEnv *, jobject, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
